# Generated by Django 4.2 on 2023-04-07 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User


from base.models import Show, Theater

def create_theater_for_existing_hosts(apps, schema_editor):
   
    for show in Show.objects.all():
        user = User.objects.get(id=show.host_id)
        theater, created = Theater.objects.get_or_create(
            user=user,
            defaults={'name': user.username}
        )
        show.host = theater
        show.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='show',
            name='genre',
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.show')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.AddField(
            model_name='show',
            name='talent',
            field=models.ManyToManyField(blank=True, to='base.talent'),
        ),
        migrations.AddField(
            model_name='show',
            name='genre',
            field=models.ManyToManyField(blank=True, to='base.genre'),
        ),
        migrations.AlterField(
            model_name='show',
            name='host',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.theater'),
            preserve_default=False,
        ),

        migrations.RunPython(create_theater_for_existing_hosts),
    ]
